on: [push, pull_request]
name: Continuous Integration

jobs:
  test:
    name: Test
    runs-on: ${{matrix.os.fullname}}
    env:
      OSU_EXECUTION_MODE: ${{matrix.threadingMode}}
    strategy:
       fail-fast: false
       matrix:
          os:
            - { prettyname: macOS, fullname: macos-latest }
          threadingMode: ['SingleThread', 'MultiThreaded']
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install .NET 5.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"

      # FIXME: libavformat is not included in Ubuntu. Let's fix that.
      # https://github.com/ppy/osu-framework/issues/4349
      # Remove this once https://github.com/actions/virtual-environments/issues/3306 has been resolved.
      - name: Install libavformat-dev
        if: ${{matrix.os.fullname == 'ubuntu-latest'}}
        run: |
         sudo apt-get update && \
         sudo apt-get -y install libavformat-dev

      - name: Compile
        run: dotnet build -c Debug -warnaserror build/Desktop.proj

      - name: Test
        run: dotnet test $pwd/*.Tests/bin/Debug/*/*.Tests.dll --blame-crash --blame-hang --settings $pwd/build/vstestconfig.runsettings --logger "console;verbosity=detailed" --logger "trx;LogFileName=TestResults-${{matrix.os.prettyname}}-${{matrix.threadingName}}.trx"
        shell: pwsh
